# Generated by Django 3.0 on 2020-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
