# Generated by Django 3.0 on 2020-03-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200319_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='body_content',
            new_name='body',
        ),
    ]
