# Generated by Django 3.0 on 2020-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200320_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
