# Generated by Django 3.0 on 2020-03-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200320_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('In Person', 'In Person'), ('Online', 'Online')], default='Online', max_length=20, null=True),
        ),
    ]
